# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Terraform/services/*

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/Terraform/Global"
              ArtifactName: "global"
              publishLocation: "Container"
            displayName: "Create Artifact for the global Folder"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.SourcesDirectory)/Terraform/services"
              ArtifactName: "services"
              publishLocation: "Container"
            displayName: "Create Artifact for the services Folder"